import { defineConfig } from 'vite-plus'

export default defineConfig({
  defaultPackage: 'apps/web',
  resolve: {
    dedupe: ['valibot'],
  },
  check: {
    fmt: true,
    lint: true,
  },
  staged: {
    '*.{js,ts,tsx,mjs,cjs,vue}': 'vp check --fix',
  },
  fmt: {
    ignorePatterns: [
      'docs/vendor/**',
      'node_modules/**',
      'dist/**',
      '.cimi/**',
      '.agent/**',
      '.agents/**',
      '.audit/**',
      '.claude/**',
      '.codex/**',
      '.continue/**',
      '.cursor/**',
      '.gemini/**',
      '.grok/**',
      '.opencode/**',
      '.pi/**',
      '.roo/**',
      '.vite-hooks/**',
      '.windsurf/**',
      'tools/oxlint/anti-slop/**',
      'packages/db/src/schema/auth.generated.ts',
      'packages/db/src/migrations/meta/**',
    ],
    singleQuote: true,
    semi: false,
  },
  lint: {
    plugins: ['unicorn', 'typescript', 'oxc', 'vue'],
    ignorePatterns: [
      'docs/vendor/**',
      'node_modules/**',
      'dist/**',
      '.cimi/**',
      '.agent/**',
      '.agents/**',
      '.audit/**',
      '.claude/**',
      '.codex/**',
      '.continue/**',
      '.cursor/**',
      '.gemini/**',
      '.grok/**',
      '.opencode/**',
      '.pi/**',
      '.roo/**',
      '.vite-hooks/**',
      '.windsurf/**',
      'tools/oxlint/anti-slop/**',
      'packages/db/src/schema/auth.generated.ts',
      'packages/db/src/migrations/meta/**',
    ],
    jsPlugins: [{ name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' }],
    rules: {
      'oxc/no-accumulating-spread': 'error',
      'anti-slop/no-array-filter-map': 'error',
      'anti-slop/no-reduce-accumulator-copy': 'error',
      'anti-slop/no-chained-type-assertions': 'error',
      'anti-slop/no-conditional-empty-object-spread': 'error',
      'anti-slop/no-known-value-widening': 'error',
      'anti-slop/no-module-mocking': 'error',
      'anti-slop/no-object-parameters': 'error',
      'anti-slop/no-reflect-apply': 'error',
      'anti-slop/no-reflect-get': 'error',
      'anti-slop/no-runtime-typeof': [
        'error',
        { allowInTypeGuards: true },
      ],
      'anti-slop/no-shape-in-symbol-names': 'error',
      'anti-slop/no-unknown-parameters': 'error',
      'anti-slop/no-unknown-returns': 'error',
      'anti-slop/no-unknown-type-aliases': 'error',
      'anti-slop/no-unsafe-dictionary-type': 'error',
      'anti-slop/no-widen-then-assert': 'error',
      'anti-slop/require-readable-spacing': 'error',
      'anti-slop/require-safety-comment-for-type-assertion': 'error',
    },
    overrides: [
      {
        files: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx'],
        rules: {
          'typescript/unbound-method': 'off',
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  run: {
    cache: {
      tasks: true,
      scripts: true,
    },
  },
})
